title: Geeky stories
email: gurdiga@gmail.com
author: Vlad GURDIGA
description: >
  If you have questions or comments, drop me a note on email. I’d be glad to
  hear from you! 🙂
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title/
twitter_username:
github_username:

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

exclude:
  - CNAME
  - Makefile
  - README.md
  - .viminfo
  - .bash_history

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

read_time: true
words_per_minute: 100

tag_archive_path: "/tags/#"
