title: Geeky stories
author: Vlad GURDIGA
logo: /images/gravatar.jpg
description: >-
  This is my personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gurdiga.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title/
twitter_username:
github_username:

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@7c881be"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

feed:
  path: atom.xml

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

exclude:
  - CNAME
  - Makefile
  - README.md
  - .viminfo
  - .bash_history

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

tag_archive_path: "/tags/#"

footer_links:
  - title: GitHub
    url: https://github.com/gurdiga
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

search_full_content: true
